version: 2.1
orbs:
  node: circleci/node@12.18.4
jobs:
  test:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Latest NPM.
          command: npm i -g npm@latest
      - run:
          name: NPM Install.
          command: npm ci
      - run:
          name: Run Test.
          command: npm run test
      - run:
          name: Run Test Coverage.
          command: npm run test:coverage
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
